version: '3.4'

services:
  examplecloudwithdocker.blazor:
    image: examplecloudwithdockerblazor
    build:
      context: .
      dockerfile: ExampleCloudWithDocker.Blazor/Dockerfile
    ports:
      - ${CLIENT_PORT}:80
      - ${CLIENT_PORT_HTTPS}:443
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  examplecloudwithdocker.api:
    image: examplecloudwithdockerapi
    build:
      context: .
      dockerfile: ExampleCloudWithDocker.Api/Dockerfile
    ports:
      - ${API_PORT}:80
      - ${API_PORT_HTTPS}:443
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}